---
title: "Introduction"
author: "Caleb Skinner"
format: pdf
---

*Is Momentum Real: On the Existence and Influences of Psychological Momentum in Professional Tennis*

# Abstract

The existence and magnitude of momentum in sports has been fiercely debated in the last forty years. Professional tennis’s repetitive and hierarchical structure has proved ideal for research, and recent studies have found evidence for momentum in professional tennis in a series of specific circumstances. Utilizing a holistic approach, this paper proposes a comprehensive definition for momentum as the derivative of the players’ smoothed point margin curve. Using the backward approximation of the derivative, we find evidence that a player’s momentum entering a point has a significant impact on his or her likelihood of winning the next point. Male players are more impacted by this effect than female players. From here, we use the forward approximation of the derivative to evaluate the impact that various characteristics have on momentum. Of note, we find strong evidence that hitting an ace, breaking serve, and winning a set tend to increase a player’s future momentum. Conversely, an interruption in play tends to diminish momentum. In general, these associations are stronger for male players than female players. These results confirm and expand upon the conclusions of established peer-reviewed research.

# Introduction

"He is feeling hot today"; "she is a streaky shooter"; "the team has seized the momentum." In modern sports culture, individuals liberally attribute results to the momentum effect. These phrases are prevalent in expert analysis, colloquial commentary, and even accounts from the players themselves. But what if these conclusions are overblown? In a landmark study, Gilovich, Vallone, & Tversky (1985) find no evidence for momentum in professional basketball players' shooting even though both fans and players expect past results to be correlated with future results. Several studies affirm this conclusion and find no evidence for momentum in baseball (Albright, 1989; Gould, 1989) and basketball (Vergin, 2000). In response, many studies published more specific evidence for momentum among horseshoe pitchers (Smith, 2003), bowling (Dorsey-Palmateer & Smith, 2004), volleyball (Raab, Gula, & Gigerenzer, 2012), american football (Roebber, Burlingame, & deWinter, 2022), and basketball (Jane, 2023). However, in recent years, professional tennis has served as the most prolific topic for momentum literature. Tennis's repetitive structure and breadth of available data facilitates more complex research. Within the last decade, several papers have discovered evidence for momentum in professional tennis within specific intervals.

This paper proposes a novel holistic definition and measurement for momentum that describes a player's momentum at any given point throughout an entire match. This measurement allows relationships discovered in several other papers to be integrated and compared in interpretable methods. We seek to synthesize these discoveries in a holistic assessment of momentum in tennis throughout an entire match. Many of the questions we ask and relationships we analyze are not unique to momentum literature, but this is the first paper seeking to incorporate the findings into a single model. Overall, our goal is twofold. First, we aim to assess the existence of momentum in a professional tennis match. Do the results of past points in a tennis match impact future results? Second, we hope to identify the relationships between several features of a tennis point and the momentum of match. What specific circumstances in past points tend to increase or decrease the future trajectory of a match?

For this study, we obtain detailed point-by-point tennis data from Jeff Sackmann's github. After cleaning the data, we have over 1.3 million points from 7715 matches in 77 different tournaments to utilize. This breadth of data allows us to evaluate momentum's behavior in specific circumstances and it's relationship with rare events. We begin by visualizing each match with a point-margin curve. We adjust the curve to account for the server of each point, and define momentum as the instantaneous rate of change or derivative of the server adjusted curve. Thus, a player's momentum is measured at each point in the match. In practice, we employ two estimations for the momentum: backward momentum and future momentum. We define backward momentum as the trend of the match entering a point, and the future momentum as the match's trajectory immediately after the point. To measure backward momentum, we exponentially smooth the server adjusted point-margin curve and then approximate the backward derivative with a simple backward gradient of the smoothed curve. Conversely, future momentum is measured with a forward gradient of the forward exponentially smoothed point-margin curve. Both backward and future momentum continuous variables centered at 0 that span from -1 to 1.

Next, we assess the effect of past results on the player's odds of winning the next point. We regress the players' backward momentum on the point victor in a logistic regression model. We control for structural variables like the players' sex, tournament, pre-match betting odds, and server of the point. We find that a half-unit increase in a player's backward momentum corresponds to a 8.03% increase in the odds of the player winning the next point. Interestingly, we find that an increase (or decrease) in backward momentum has a larger impact on men than women. A half-unit increase in a male player's backward momentum corresponds to a 9.85% increase in the odds of winning a point. On the other hand, a half-unit increase in a female player's backward momentum corresponds to a 5.31% increase in the odds of winning a point. After verifying the results with a few procedures, we have sufficient evidence to conclude that past results do impact future results. That is, momentum does exist in professional tennis.

In the second stage, we seek to understand the relationship between several events and the future trend of the match. We hope to identify the events that carry a meaningful association. We divide our events into two models; a point-level model full of factors with short-term impact and a game-level model comprised of factors with long-term impact. Together, the two models demonstrate that winning is associated with an increase in future momentum. Tennis is a hierarchical sport, and the model finds that the more significant victories are associated with a larger increase in future momentum. Important events like converting a break point have a strong association with an increase in future momentum, and memorable events like striking an ace or hitting a winner tend to increase future momentum. On the other hand, we find that interruptions in play tend to diminish the association between winning and future momentum. As in the first stage, we find larger effect sizes for men than women. Overall, these results affirm and expand upon the findings of recent momentum literature on professional tennis.