---
title: "Literature Review"
author: "Caleb Skinner"
date: April 16, 2024
format:
  pdf:
    linestretch: 2
    include-in-header:
      text: |
        \pagenumbering{gobble}
    header-includes: |
        \usepackage{indentfirst}
        \setlength{\parindent}{2em}
font-family: Times New Roman
fontsize: "12pt"
geometry:
      - top=25.4mm
      - left=25.4mm
      - right=25.4mm
      - bottom=25.4mm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#", fig.height = 3, 
  cache = FALSE,  collapse = TRUE,
  error = TRUE, echo = FALSE,
  message = FALSE)
```

\pagenumbering{arabic}

It is strikingly easy for one to overestimate the relationship between past and future success. In fact, individuals struggle to identify casual relationships as a whole. People are prone to look for patterns but are, unfortunately, poor “intuitive statisticians.” We identify these patterns, but all too often they are examples of spurious correlation (Kahneman, 2011). Why is this? In general, humans misunderstand the nature of random sequences. One tends to underestimate the length and frequency of random strings of wins and losses (Gilovich, Vallone, & Tversky, 1985). In other words, flip 100 coins, and most would underestimate the size of the largest number of consecutive heads or tails. This underestimation leads to improper conclusions. Even when informed that a game is purely random, one tends to deny the independence of successive points (Page & Coates, 2017). Thus, even when individuals know randomness is completely responsible, they still want to draw conclusions. These misconceptions lead individuals to attribute consecutive victories to momentum, when, in fact, randomness is entirely responsible.

This inward shortcoming is compounded by societal pressures and customs. The frequent and arbitrary colloquial use of momentum in sporting events encourages observers for identifying and emphasizing when they believe teams and players have “seized the momentum” or are “feeling hot” (Vergin, 2000). Observers are looking for momentum. They want to find it. This leads to confirmation bias, a well-known psychological error, where individuals tend to process, interpret, and remember information in a way that is consistent with their existing beliefs (Oswald & Grosjean, 2004). This phenomenon gives the casual observer incentive to notice and remember streaks of consecutive success - or failures - while forgetting interruptions or exceptions. Early research on momentum has supported these biases. An analysis on shooting trends in professional basketball players showed that both fans and players are inclined to believe that a player’s likelihood of making a shot are greater after a make than after a miss. The same study failed to find evidence for any relationship (Gilovich, Vallone, & Tversky, 1985). More recently, Briki et al. (2014) found that observers are prone to overestimate the effects of momentum on table tennis players. The observers expected players to be more highly affected by adverse conditions than they actually were. Altogether, these biases create an environment where events are frequently misclassified as momentum.

Fortunately, many researchers have approached the subject and conducted extensive and creative analysis on the existence and effect of momentum. They have drawn several nuanced conclusions, and their insight has proved fundamental. However, like many complex subjects, comprehensive clarity is scarce. Broadly, there are three overlapping frameworks for explaining momentum: biological, psychological, and economic (Morgulev, 2023).

## Biological Framework

First, biological researchers have focused their efforts on discovering momentum in the animal kingdom. They suggest that ‘winning’ produces positive hormones that prime animals for future success. This theoretical concept, known as the ‘winner effect’, indicates that past positive winning experiences award individuals a higher likelihood for future victories largely due to inward physiological reactions to winning (Robertson, 2012). In the biological framework, the victory physically improves the animal’s demeanor and skill set. This is because victories emit enhancing hormones like testosterone, estrogen, and cortisol into the body’s bloodstream. This theory has been generally supported by experimental research. For example, testosterone levels increased in humans after victory in the classic video game Tetris and decreased after a loss (Zilioli & Watson, 2014). In a study involving male sprinters, high testosterone levels were positively associated with a lower sprint time (Bezuglov et al., 2023). In other words, high levels of testosterone are found to be linked with increased performance. In addition, these hormones are supposed to increase confidence, aggression, and positivity in the individual. This behavior may intimidate and frighten competitors and position the animal in a mindset and circumstance prepared for future success (Morgulev, 2023). Winning animals are more likely to participate in future competitions, and, therefore, experience success.

Overall, researchers have found existence of the winner effect in several animal species. Jumping spiders’ fighting ability increased after victory (Kasumovic et al., 2010). Fighting behaviors and aggression in pupfish were impacted by victory (Hsu & Wolf, 2001). Previous outcomes directly impacted the probability of victory for lizards (Garcia et al., 2014). In a comprehensive analysis that spanned several animals, the probability of victory nearly doubles for winners when accounting for asymmetries in the competitor’s skill (Rutte et al., 2006). Measuring the winner effect in humans, however, is much more difficult and the results are more nuanced.

## Psychological Framework

In the second framework, competition and momentum are examined from a purely psychological perspective. Psychologists acknowledge the physiological changes that biologists propose, but their focus is on the psychological factors impacting the competitors (Morgulev, 2023). As such, psychological momentum is associated with confidence and the popular adage ‘success breeds success.’ Typically, this research resides in the domain of sports psychology. Adler & Adler (1978) propose that a series successful events like a steal, dunk, or ace can serve as catalysts of momentum. These catalysts build and contribute to increased confidence and motivation within an individual. Iso-Ahola & Mobily (1980) coined the term psychological momentum to describe the effect of these psychological factors on a competitor. They write “psychological momentum is an added or gained psychological power which changes a person’s view of himself or of others or others’ view of him and of themselves.” Taylor & Demick (1994) contributed heavily to the theory of psychological momentum. They propose a six-stage multidimensional model outlining its progression. This “momentum chain” is as follows: (a) precipitating event, (b) change in cognition, affect, or physiology, (c) change in behavior, (d) increase or decrease in performance, (e) opposite reaction in opponent, and (f) change in outcome. Much of the individual links in the model has yet to be directly empirically verified, but, as predicted, positive preceding events are associated with a large array of cognitive and behavioral benefits. Vallerand & Reid (1988) links psychological momentum with the notion that one is “progressing towards his/her goal” which in turn reinforces feelings of self-confidence, control, and motivation. Self-confidence is supposed to increase attentiveness, concentration, and even the mental and physical effort of competitors (Iso-Ahola & Mobily, 1980). Briki (2017) argue that past success yields behavioral patterns like persistence and self-determination. Initially, Iso-Ahola & Mobily (1980) proposed that, all else equal, the player with the higher psychological momentum receives a competitive advantage. However, years of mixed results has brought uncertainty into that conclusion.

## Economic Framework

Economists often view momentum from a game theory perspective. They define contests as “games” between two players who earn a payoff from the game. Payoffs are a numerical estimation of the worth of each outcome to each player. Monetary rewards contribute to this payoff, but so do social and intrinsic rewards (Vojnovic, 2015). In these contests, players have the opportunity to exert different levels of effort which affect their chances of receiving each payoff. However, effort is costly and lessens the players payoffs (Morgulev, 2023). Thus, in order to maximize their payoff, players have incentive to minimize effort. Theoretically, this means that the structure and payoff of a game make the players’ effort predictable (Malueg & Yates, 2010).

The structure of a game incorporates the rules, circumstances, and score of the game itself. Each game is comprised of a large sequence of small “battles” (Kovenock & Roberson, 2012). As these battles occur, inevitably one player will have an advantage, shifting the structure of the game. In essence, this shift creates a new game in which one player is closer to winning than the other. The losing player must now expend more effort than his/her counterpart to achieve victory (Morgulev, 2023). Effort is costly, so this new game has asymmetric incentives that impact the players’ predicted effort (Konrad & Kovenock, 2009). This change in effort is known as *strategic momentum*. Strategic momentum ignores inward psychological or physiological factors and instead focuses entirely on the change in the game’s structure.

Mago, Sheremeta, & Yates (2012) give a simple illustration using a best of three contest between two equally-skilled players. At the start, economic theory postulates that both players will exert equal effort. However, after one round, the winning player has an advantage. They must exert enough effort to win one round while the losing player must win two. The leading player, armed with strategic momentum, has more incentive to expend energy and thus has a higher chance of winning the second round. If the players are again tied after two rounds, this economic theory predicts that in round three each player has equal incentive to exert effort- and therefore win. This corroborates with empirical studies, which find that equally-skilled players are equally likely to win a third set in best of three set tennis matches (Malueg & Yates, 2010).

## Interactions between the Frameworks

While independent, these three frameworks contain several notable similarities and distinctions. The biological and psychological frameworks both emphasize the effect of winning on the individual. The biological framework emphasizes the chemical and physiological changes in the winner, while the psychological framework assesses the behavioral and psychological changes. Morgulev & Avugos (2020) integrate the two frameworks under the term *psychophysiological momentum*.

Strategic momentum, however, is distinct from both other frameworks. Strategic momentum assesses the situation, while biological and psychological momentum evaluate the competitors themselves. Researchers are interested in distinguishing the frameworks, but in most contests, both types of momentum co-exist (Cohen-Zada, Krumer, & Shtudiner, 2017), so separation is difficult. However, several researchers have constructed laboratory experiments or identified natural experiments to isolate strategic and psychological momentum. For example, Mago, Sheremeta, & Yates (2012) conducted a laboratory experiment, using varying prizes as incentives in best of three contests, and they found evidence for strategic momentum but not for psychological momentum. In contrast, an analysis of professional judo tournaments found that judo players arriving at a bronze medal fight after a win are more likely to win than a player arriving after a loss (Cohen-Zada, Krumer, & Shtudiner, 2017). This unique setting lacks strategic momentum, but contains psychological momentum. Likewise, Meier et al. (2020) assess interruptions in tennis contests and find evidence that psychological momentum and not strategic momentum is the main driver of a performance increase. Several researchers, therefore, argue that the value of psychological momentum exceeds that of strategic momentum (Descamps, Ke, & Page, 2022; Morgulev, 2023). The findings of Depken, Gandar, & Shapiro (2022) are more nuanced. They design a model based purely on incentives from strategic momentum and interpret deviations as psychological momentum. Under this interpretation, they find evidence for a *psychological reversal* after set one and weak evidence for psychological momentum after set two. Altogether, strategic and psychophysiological momentum both exist, but the dominance of one over the other often depends on the design and situation of the empirical study.

## Procrastination and Anti-Momentum Theory

Economic theory is not unanimously convinced that success breeds success. Success leads to favorable, comfortable situations that can dissuade individuals from expending effort towards a future goal. Colloquially, this is known as procrastination. Behavioral economics introduces procrastination into decision making through the concept *hyperbolic-discounting*. Hyperbolic-discounting is a cognitive bias, where individuals tend to value smaller immediate rewards higher than larger future rewards. Phelps & Pollak (1968) introduced the concept, and Laibson (1997) popularized and justified it. He argues that laboratory and field studies demonstrate that humans disproportionately value the future (Ainslie & Haslam, 1992). Laibson writes that the hyperbolic discounting structure “sets up a conflict between today’s preferences, and the preferences that will be held in the future.” In essence, “the hyperbolic discounting approach captures the psychological phenomenon that the present is given special treatment” (Rubinstein, 2003). Shigeta (2022) illustrates hyperbolic discounting by separating the utility and consumption of an agent’s current self from the utility and consumption of his or her future self. If the future is far enough away, the current self effectively treats the future self as a different individual. Psychologically, this inconsistency is categorized as a lack of self-control and a misunderstanding of the importance of the future (Laibson, 1997). Overall, the model has been widely applied to a variety of financial situations like investment planning (Laibson 1997) and corporate finance (Grenadier & Wang, 2007). Evidence has been found to support hyperbolic discounting in the job search market (Paserman, 2008) as well as procrastination, addiction, information acquisition, and self-regulation (Rubinstein, 2003). There is very little empirical research to apply the theory of hyperbolic discounting to contests, but the theory translates. Under the hyperbolic discounting model, individuals value time and energy in the present more highly than in the future. Thus, players with many opportunities to secure victory will be motivated to exert less effort in the early opportunities and potentially “procrastinate” victory.

## Momentum in Sports

The presence of momentum or “streakiness” in sports has fallen under considerable debate in the last forty years. Gilovich, Vallone, & Tversky (1985) published a landmark report comprehensively rejecting the notion of the “hot hand” in basketball. In both live shooting and free throw attempts, they find no evidence that a made basket positively impacts a player’s chances to make the subsequent shot. In addition, they find no evidence that the number of runs of consecutive makes or misses differs from the predicted number of runs governed entirely by chance. A few years later, Albright (1989) came to a similar conclusion with hitting streaks in baseball. He found that baseball players as a whole do not exhibit streakiness beyond the scope of randomness. In fact, Gould (1989) concluded that Joe DiMaggio’s 56-game hitting streak in 1941 was the only known exception. Vergin (2000) expanded these conclusions to teams as a whole, finding that winning streaks from both professional basketball and professional baseball teams are comparable to the results expected if the games were determined independent of each other. These results and more have led Bar-Eli, Avugos, & Raab (2006) to conclude after an extensive review that little empirical evidence supports the relationship between past and future success.

However, several studies have found empirical evidence for momentum in sports. Smith (2003) found a “hot hand” effect in horseshoe pitchers. He argues that horseshoe competitions have many structural properties that eliminate confounding variables present in other sports. Smith (2003) posits that the small duration between pitches and little strategic complications play a large part in the findings. In a similarly simple game, Dorsey-Palmateer & Smith (2004) found evidence for streakiness in bowling. They found that bowlers are more likely to roll a strike after a series of strikes than a series of non-strikes. Recently, papers have found evidence for momentum in more complex sports. This is potentially a direct result of increased access to large data sets (Jane, 2023). Raab, Gula, & Gigerenzer (2012) find evidence for streakiness in half of the volleyball players and conclude that the hot hand effect exists in volleyball. Shea (2013) finds evidence for streakiness in professional basketball’s three-point contests and professional baseball’s home run derby. Like previous findings, he argues that the simplicity of these games allows for more direct analysis and removes potential structural or strategic challenges. An analysis of the change in win probability in professional football indicates that team’s possessions are dependent and that long streaks of successful drives are more likely than randomness would suggest (Roebber, Burlingame, & deWinter, 2022). In a challenge to Gilovich, Vallone, & Tversky’s foundational paper, Jane (2023) finds evidence for both a hot hand and choking under pressure on free throw attempts in professional basketball.

## Momentum in Tennis

The game of tennis holds incredible value for researchers because of its simple and repetitive structure. Players are continually exposed to the same conditions and are not subject to the complex interactions and strategic decisions that impact the dynamic of many team sports (Sarcevic, Vranic, & Pintar, 2021). In addition, tennis has been described as a best-of-n and tug-of-war game (Gauriot & Page, 2019). This hierarchical scoring structure makes it easier to identify asymmetric incentives between the players and assess momentum. In singles, there are always two possible outcomes and two players. This provides two significant empirical advantages. First, after each point in the match, one player always inches closer to his or her goal in a measurable way. There are no neutral outcomes. Second, the same two players compete for the entire duration of the match. This makes it possible to adjust for any inequality in skill between the two players in a more controlled fashion. These structural benefits and the abundance of available data have made tennis to be an ideal sport to analyze the presence of momentum.

Klaasen & Magnus (2001) delivered the first major contribution towards momentum literature in tennis with the conclusion that points at Wimbledon are not independent and identically distributed. While controlling for the quality of the players, they find that winning the previous point positively impacts players chances of winning the subsequent point. However, they concluded that the deviation is small enough that researchers can safely assume the points are independent and identically distributed.

Other researchers have noticed that not all points in tennis are the same. In his famous book *Winning Ugly*, famous tennis coach Brad Gilbert argues that “specific points and games” have an outsized impact “on the momentum and outcome of the match” (Gilbert & Jamison, 2013). These uniquely impactful points then have a potential to be exploited by researchers to assess their momentum effect. Page & Coates (2017) assessed the effect of long tiebreaks in the first set on future sets. The two players end these sets having played about 78 points, but the outcomes of sets with long tiebreaks are ultimately decided by only two points. Thus, after the set’s conclusion, the two players will have won about the same amount of points, but one player will have emerged with a massive strategic and psychological advantage. In men’s matches, they find that in first set tiebreaks lasting longer than 20 points, the winner of the first set has a 60% chance of winning the second set. They conclude that winning a close set produces momentum. They attribute this advantage to the winner effect.

Similarly, Gauriot & Page (2019) assess the effect of shots landing close to lines on future points. If a player hits a ball that lands one centimeter outside the line, he or she has a 0% chance of winning the point, but if the player hits a ball that lands one centimeter in, he or she has a positive probability of winning the point. Thus, within these few centimeters there is a large discontinuity in the outcome of the point. In men’s matches, they find that shots close to lines give players a higher chance to win the next point. Interestingly, this effect increases when the game score is tied or near its conclusion and falls when the score is asymmetric. Gauriot & Page (2019) conclude that the effect is strongest when the match is close and nearing its end.

Meier et al. (2020) exploit the hierarchical structure of tennis by assessing the effect of breaking the opponent’s serve on future points. Breaks of serve are uncommon and often sufficient in determining the winner of a set (Klaasen & Magnus, 2001). A server’s chance of winning his service game increases by almost 9 percentage points after a break (Meier et al., 2020). However, if players are interrupted by a changeover in between the break and the subsequent service game, the effect is drastically decreased. Meier et al (2020) conclude that psychological momentum - not strategic momentum - primarily causes the effect.

Overall, several studies find a larger momentum effect in men than in women. Depken, Gandar, & Shapiro (2022) analyze the set-level momentum effects and find significant differences in male and female responses in sets one and two of a best-of-three set match. Page & Coates (2017) found a winner effect in men’s players after winning a close tiebreak, but they failed to find a winner effect for women. Gauriot & Page (2019) also fail to find any significant patterns for women’s matches after a shot lands close to the line. They, however, leave open the possibility that momentum exists in women’s tennis. This distinction between male and female contributors aligns with conclusions from other fields (Cohen-Zada, Krumer, & Shtudiner, 2017) and fits with physiological explanations derived from the biological framework (Bezuglov et al., 2023).

## Summary

Altogether, existing research suggests that momentum is difficult to assess. Humans are quick to identify patterns of momentum, but these patterns are frequently spurious. Yet, there is a growing domain of literature that supports the presence of momentum and three frameworks that explain it. The biological framework introduces the winner effect and suggests that winning produces positive hormones that orient the competitor for future success. The psychological framework holds that success breeds confidence, motivation, and general positive feelings that increase concentration, attentiveness, and future success. This process is known as psychological momentum. The economic framework introduces strategic momentum and holds that small victories in a competition change the competition’s structure and motivate winners to exert more energy than losers. However, the economic field is not unanimous. In direct contrast to the strategic momentum, the concept of hyperbolic discounting theorizes that players in successful positions will procrastinate effort to future moments in the competition.

Initial empirical studies in sports found very little support for momentum. Gilovich, Vallone, & Tversky (1985) rejected the notion of the hot hand in basketball, and Albright (1989) dismissed streakiness in baseball hitting. These findings left a mark on the field and at the very least demonstrate that momentum is more nuanced and often less impactful than observers would expect. Recently, an increase in accessible and detailed data has allowed for more specific and nuanced studies on momentum. These studies have contributed to growing evidence for the existence of momentum in sports.

Tennis’s simple and hierarchical structure has provided a suitable ground for empirical studies. Researchers observe changes in momentum after several distinct moments in a match. Klaasen & Magnus (2001) find evidence for momentum after winning a point. Page & Coates (2017) conclude that winning a close set generates momentum for future sets. Gauriot & Page (2019) find that shots landing close to the line generate positive momentum. This effect is strongest when the match is close and nearing its end. Meier et al. (2020) find evidence that a break of serve yields positive momentum, but that interruptions in play dampen momentum. Finally, most of these studies find much stronger evidence for momentum in men’s tennis than in women’s tennis.