---
title: "Is Momentum Real: On the Existence and Influences of Psychological Momentum in Professional Tennis"
author: "Caleb Skinner"
format:
  pdf:
    toc: true
    toc-depth: 2
    linestretch: 2
    include-in-header:
      text: |
        \pagenumbering{gobble}
    header-includes: |
        \usepackage{indentfirst}
        \setlength{\parindent}{2em}
        \usepackage[all]{nowidow}
        \hyphenpenalty=10000
    template-partials:
      - toc.tex
linkcolor: black
font-family: Times New Roman
fontsize: "12pt"
tbl-cap-location: "top"
fig-cap-location: "top"
geometry:
      - top=25.4mm
      - left=38.1mm
      - right=25.4mm
      - bottom=25.4mm
---

\newpage

\pagenumbering{arabic}
\addtocounter{page}{105}

\begin{spacing}{1}
\vspace*{.1mm}
\begin{center}
\setlength{\parskip}{24pt}

REFERENCES

\end{center}
\end{spacing}

```{=latex}
\begin{spacing}{1}
\setlength{\parindent}{0em}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{16pt}
\noindent
```

Adler, Peter, and Patricia A. Adler. "The role of momentum in sport." Urban Life 7, no. 2 (1978): 153-175.

Ainslie, George, and Nick Haslam. "Hyperbolic discounting." (1992).

Albright, S. Christian. "A statistical analysis of hitting streaks in baseball." Journal of the american statistical association 88, no. 424 (1993): 1175-1183.

Bar-Eli, Michael, Simcha Avugos, and Markus Raab. "Twenty years of “hot hand” research: Review and critique." Psychology of Sport and Exercise 7, no. 6 (2006): 525-553.

Bezuglov, Eduard, Maria Shoshorina, Artemii Lazarev, Anton Emanov, Egana Koroleva, Ilsyuyar Anishchenko, Zbigniew Waśkiewicz, Mikhail Butovskiy, and Ryland Morgans. "Does vitamin D affect strength and speed characteristics and testosterone concentration in elite young track and field athletes in the North European summer?." Nutrition Journal 22, no. 1 (2023): 16.

Briki, Walid, Julie Doron, Keith D. Markman, Ruud JR Den Hartigh, and Christophe Gernigon. "Differential reactions of virtual actors and observers to the triggering and interruption of psychological momentum." Motivation and Emotion 38 (2014): 263-269.

Briki, Walid. "Rethinking the relationship between momentum and sport performance: Toward an integrative perspective." Psychology of Sport and Exercise 30 (2017): 38-44.

Cohen-Zada, Danny, Alex Krumer, and Ze'ev Shtudiner. "Psychological momentum and gender." Journal of Economic Behavior & Organization 135 (2017): 66-81.

Crespo, M., M. Reid, D. Miley, and F. Atienza. "The relationship between professional tournament structure on the national level and success in men's professional tennis." Journal of Science and Medicine in Sport 6, no. 1 (2003): 3-13.

Depken, Craig A., John M. Gandar, and Dmitry A. Shapiro. "Set-level strategic and psychological momentum in best-of-three-set professional tennis matches." Journal of Sports Economics 23, no. 5 (2022): 598-623.

Descamps, Ambroise, Changxia Ke, and Lionel Page. "How success breeds success." Quantitative Economics 13, no. 1 (2022): 355-385.

Dorsey-Palmateer, Reid, and Gary Smith. "Bowlers' hot hands." The American Statistician 58, no. 1 (2004): 38-45.

Durbin, James, and Geoffrey S. Watson. "Testing for serial correlation in least squares regression. III." Biometrika 58, no. 1 (1971): 1-19.

Easton, Stephen, and Katherine Uylangco. "Forecasting outcomes in tennis matches using within-match betting markets." International Journal of Forecasting 26, no. 3 (2010): 564-575.

Garcia, Mark J., Joseph Murphree, Jonathan Wilson, and Ryan L. Earley. "Mechanisms of decision making during contests in green anole lizards: prior experience and assessment." Animal Behaviour 92 (2014): 45-54.

Gauriot, Romain, and Lionel Page. "Does success breed success? A quasi-experiment on strategic momentum in dynamic contests." The Economic Journal 129, no. 624 (2019): 3107-3136.

Gelman, Andrew, and Jennifer Hill. Data analysis using regression and multilevel/hierarchical models. Cambridge university press, 2007.

Gilbert, Brad, and Steve Jamison. Winning ugly: Mental warfare in tennis--lessons from a master. Simon and Schuster, 2013.

Gilovich, Thomas, Robert Vallone, and Amos Tversky. "The hot hand in basketball: On the misperception of random sequences." Cognitive psychology 17, no. 3 (1985): 295-314.

Gómez-de-Mariscal, Estibaliz, Vanesa Guerrero, Alexandra Sneider, Hasini Jayatilaka, Jude M. Phillip, Denis Wirtz, and Arrate Muñoz-Barrutia. "Use of the p-values as a size-dependent function to address practical differences when analyzing large datasets." Scientific reports 11, no. 1 (2021): 20942.

Gould, Stephen Jay. “The Streak of Streaks.” CHANCE 2, no. 2 (1989): 10–16. doi:10.1080/09332480.1989.10554932.

Grenadier, Steven R., and Neng Wang. "Investment under uncertainty and time-inconsistent preferences." Journal of Financial Economics 84, no. 1 (2007): 2-39.

Hosmer Jr, David W., Stanley Lemeshow, and Rodney X. Sturdivant. Applied logistic regression. John Wiley & Sons, 2013.

Hsu, Yuying, and Larry L. Wolf. "The winner and loser effect: what fighting behaviours are influenced?." Animal Behaviour 61, no. 4 (2001): 777-786.

Hyndman R (2023). "fpp3: Data for "Forecasting: Principles and Practice" (3rd Edition)." R package version 0.5

Hyndman, R.J., & Athanasopoulos, G. (2021) Forecasting: principles and practice, 3rd edition, OTexts: Melbourne, Australia. 

Iso-Ahola, Seppo E., and K. E. N. Mobily. "“Psychological momentum”: A phenomenon and an empirical (unobtrusive) validation of its influence in a competitive sport tournament." Psychological Reports 46, no. 2 (1980): 391-401.

Jane, Wen‐Jhan. "Hot hand or choking under pressure–Evidence from professional basketball." Kyklos 76, no. 2 (2023): 223-254.

Kahneman, Daniel. Thinking, fast and slow. macmillan, 2011.

Kasumovic, Michael M., Damian O. Elias, Senthurran Sivalinghem, Andrew C. Mason, and Maydianne CB Andrade. "Examination of prior contest experience and the retention of winner and loser effects." Behavioral Ecology 21, no. 2 (2010): 404-409.

Klaassen, Franc JGM, and Jan R. Magnus. "Are points in tennis independent and identically distributed? Evidence from a dynamic binary panel data model." Journal of the American Statistical Association 96, no. 454 (2001): 500-509.

Konrad, Kai A., and Dan Kovenock. "Multi-battle contests." Games and Economic Behavior 66, no. 1 (2009): 256-274.

Kovenock, Dan, and Brian Roberson. "Coalitional Colonel Blotto games with application to the economics of alliances." Journal of Public Economic Theory 14, no. 4 (2012): 653-676.

Kuhn et al., (2020). Tidymodels: a collection of packages for modeling and machine learning using tidyverse principles.

Kuhn, M, and K Johnson. 2013. Applied Predictive Modeling. Springer.

Laibson, David. "Golden eggs and hyperbolic discounting." The Quarterly Journal of Economics 112, no. 2 (1997): 443-478.

Lin, Mingfeng, Henry C. Lucas Jr, and Galit Shmueli. "Research commentary—too big to fail: large samples and the p-value problem." Information Systems Research 24, no. 4 (2013): 906-917.

Mago, Shakun D., Roman M. Sheremeta, and Andrew Yates. "Best-of-three contest experiments: Strategic versus psychological momentum." International Journal of Industrial Organization 31, no. 3 (2013): 287-296.

Malueg, David A., and Andrew J. Yates. "Testing contest theory: evidence from best-of-three tennis matches." The Review of Economics and Statistics 92, no. 3 (2010): 689-692.

Meier, Philippe, Raphael Flepp, Maximilian Ruedisser, and Egon Franck. "Separating psychological momentum from strategic momentum: Evidence from men’s professional tennis." Journal of economic psychology 78 (2020): 102269.

Morgulev, Elia. "Success breeds success: Physiological, psychological, and economic perspectives of momentum (hot hand)." Asian Journal of Sport and Exercise Psychology (2023).

Morgulev, Elia, and Simcha Avugos. "Beyond heuristics, biases and misperceptions: the biological foundations of momentum (hot hand)." International Review of Sport and Exercise Psychology 16, no. 1 (2023): 155-175.

Oswald, Margit E., and Stefan Grosjean. "Confirmation bias." Cognitive illusions: A handbook on fallacies and biases in thinking, judgement and memory 79 (2004): 83.

Page, Lionel, and John Coates. "Winner and loser effects in human competitions. Evidence from equally matched tennis players." Evolution and Human Behavior 38, no. 4 (2017): 530-535.

Paserman, M. Daniele. "Job search and hyperbolic discounting: Structural estimation and policy evaluation." The Economic Journal 118, no. 531 (2008): 1418-1452.

Phelps, Edmund S., and Robert A. Pollak. "On second-best national saving and game-equilibrium growth." The Review of Economic Studies 35, no. 2 (1968): 185-199.

R Core Team (2024). "R: A Language and Environment for Statistical Computing." R Foundation for Statistical Computing, Vienna, Austria.

Raab, Markus, Bartosz Gula, and Gerd Gigerenzer. "The hot hand exists in volleyball and is used for allocation decisions." Journal of Experimental Psychology: Applied 18, no. 1 (2012): 81.

Reinhart, Alex. "A review of self-exciting spatio-temporal point processes and their applications." Statistical Science 33, no. 3 (2018): 299-318.

Robertson, Ian. The winner effect: How power affects your brain. A&C Black, 2012.

Roebber, Paul J., Bryan M. Burlingame, and Anthony deWinter. "On the existence of momentum in professional football." Plos one 17, no. 6 (2022): e0269604.

Royle, J. Andrew, and Robert M. Dorazio. Hierarchical modeling and inference in ecology: the analysis of data from populations, metapopulations and communities. Elsevier, 2008.

Rubinstein, Ariel. "“Economics and psychology”? The case of hyperbolic discounting." International Economic Review 44, no. 4 (2003): 1207-1216.

Rutte, Claudia, Michael Taborsky, and Martin WG Brinkhof. "What sets the odds of winning and losing?." Trends in Ecology & Evolution 21, no. 1 (2006): 16-21.

Sackmann, Jeff. "Grand Slam Point-by-Point Data, 2011-present." GitHub repository.

Šarčević, Ana, Mihaela Vranić, and Damir Pintar. "A combinatorial approach in predicting the outcome of tennis matches." International Journal of Applied Mathematics and Computer Science 31, no. 3 (2021): 525-538.

Shea, Stephen. "In support of a hot hand in professional basketball and baseball." PsyCh journal 3, no. 2 (2014): 159-164.

Shigeta, Yuki. "Quasi-hyperbolic discounting under recursive utility and consumption–investment decisions." Journal of Economic Theory 204 (2022): 105518.

Skinner, Caleb. "Analyzing Traits and Tendencies in Professional Tennis Players." (2023)

Smith, Gary. "Horseshoe pitchers’ hot hands." Psychonomic bulletin & review 10 (2003): 753-758.

Song, ChiUng, Bryan L. Boulier, and Herman O. Stekler. "The comparative accuracy of judgmental and model forecasts of American football games." International Journal of Forecasting 23, no. 3 (2007): 405-413.

Taylor, Jim, and Andrew Demick. "A multidimensional model of momentum in sports." Journal of Applied Sport Psychology 6, no. 1 (1994): 51-70.

Tennis Data. "Match Results and Betting Odds, 2000-present." Tennis Data.

Vallerand, Robert J., and Greg Reid. "On the relative effects of positive and negative verbal feedback on males' and females' intrinsic motivation." Canadian Journal of Behavioural Science/Revue canadienne des sciences du comportement 20, no. 3 (1988): 239.

Vergin, Roger C. "Winning Streaks in Sports and the Misperception of Momentum." Journal of Sport Behavior 23, no. 2 (2000).

Vojnović, Milan. Contest theory: Incentive mechanisms and ranking methods. Cambridge University Press, 2015.

Wickham, Hadley, and Garrett Grolemund. R for data science. "O'Reilly Media, Inc.", 2017.

Zilioli, Samuele, and Neil V. Watson. "Testosterone across successive competitions: Evidence for a ‘winner effect’ in humans?." Psychoneuroendocrinology 47 (2014): 1-9.

```{=latex}
\end{spacing}
```